_wandb:
    value:
        cli_version: 0.23.1
        e:
            qaeldaivqbcaqq7h5m2hhnpog7ga2rd2:
                args:
                    - --base_path=/home/leehw/project/smartphone_defect_segmentation/
                    - --use_wandb
                codePath: script/train.py
                codePathLocal: script/train.py
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1081101176832"
                        used: "29981384704"
                email: adhoc0909@khu.ac.kr
                executable: /home/leehw/miniconda3/envs/pytorch/bin/python
                git:
                    commit: cede4158767759ffcd5310ad77224319662741fe
                    remote: https://github.com/adhoc0909/smartphone_defect_segmentation.git
                gpu: NVIDIA GeForce RTX 4060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "17175674880"
                      name: NVIDIA GeForce RTX 4060 Ti
                      uuid: GPU-6647cbee-3ed0-5c43-a88e-e109ab197e19
                host: DESKTOP-3D2T16A
                memory:
                    total: "16669380608"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/leehw/project/smartphone_defect_segmentation/./script/train.py
                python: CPython 3.12.12
                root: /home/leehw/project/smartphone_defect_segmentation
                startedAt: "2026-01-03T09:08:30.490092Z"
                writerId: qaeldaivqbcaqq7h5m2hhnpog7ga2rd2
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.12.12
            "5": 0.23.1
            "8":
                - 2
            "12": 0.23.1
            "13": linux-x86_64
base_channels:
    value: 32
batch_size:
    value: 8
bce_weight:
    value: 0.5
epochs:
    value: 50
img_h:
    value: 144
img_w:
    value: 256
loss:
    value: BCEDice
lr:
    value: 0.001
model:
    value: unet
seed:
    value: 42
test_ratio:
    value: 0.15
threshold:
    value: 0.5
train_ratio:
    value: 0.7
weight_decay:
    value: 0
